let data = [
  {
    "id":1,//入院日期
    "enterHospitalDate":1234567,
    "diagnosis":[
      "腹主动脉瘤",
      "wwww"
    ],//手术记录
    "operation":[
      {
        "id":1,
        "operationName":"手术名称",
        "operationDate":"手术日期",
        "surgeon":"手术医师",
        "anesthesiaType":"麻醉方式",
        "anesthesiaPerson":"麻醉医生",
        "operationStep":"手术步骤",
        "consumables":{
          "total":10,
          "list":[
            {
              "property":"介入耗材",
              "name":"耗材名称",
              "brand":"品牌规格",
              "count":2
            }
          ]
        }
      }
    ],//出院记录
    "diagnosedRecord":{
      "id":1,
      "leaveHospitalDate":1234567,
      "enterHospitalDate":123456,
      "illnessComplaint":"主诉",
      "enterHospitalSituation":"入院情况",
      "diagnosis":"诊断经过",
      "diagnosedSituation":"出院情况",
      "dischargeInstructions":"出院医嘱",
      "dischargedWithMedicine":"出院带药"
    },
    "resource":[
      {
        "id":1,
        "type":"pictuire|video|ppt",
        "thumbtail":"....缩略图",
        "downloadurl":".....下载地址",
        "date":123456
      }
    ]
  }
]